sudo: required

language: python

services:
  - docker

before_install:

script:
  - docker-compose --version
  - docker --version
  - ./run-tests.sh

notifications:
    email: false

after_success:
  - pip install coveralls
  - coveralls

jobs:
  include:
  - python: "2.7.13"
    env: PYTHON_VERSION=2.7.13
  - python: "3.7"
    env: PYTHON_VERSION=3.7
  - python: "3.8"
    env: PYTHON_VERSION=3.8

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      lExKYluVHK4Xbvl8aO17SHZ0A+PkZUaLvZfhRdzWwvy3hPh1EHTZQhiYP7TaLI/Fzu0hEXo430KuDYG5pzlP28BUHBlmmMCTD03mQBo2+KEYk
      2eeCFVZNDhaXO3vi6a+ogIYVSgGA0wE7UGok/JYr+fmyIImRy/YA62ggAurgmS65TcgkYiI1K9jbhRPBAdU8pU3QxZJTUAPPCdePgURw5CM0J
      Or7NQeSiyZaGczoLmgF15+204+jKI4PC7JCVDeDLWVxSvjylDa80LL6f24KXpkjx3YRlEv++Dlt3Av/S46r0zzI27MhDX+LO2zHmJcHXMWEA0
      KN/1XQ29352ZE+m60HbzjEDdDRunSPZ6ivBvXrgl4Jvc597oQHXObXJHdL4AqkJ1/V4qbxrY5ljYZsINN1q+Vh8ooP/zzOLjIjdVcOXry2ReL
      Bl+LyFG4z59x+NG8mDbzjB9E6KwQkXDf1J5cTtKrk2JUX/gkujma+nnrhVqLzJ3CC9FYqW5NrCDRpBVFPSNt4EjSO5T8U1Hq3UR7A3cUJ9ZKe
      HlrWQkuCHsTAuq5vwSwFgPIyZfld5Ab7YMGl4JlWGd2KkytDnfRN8qoF/HMCAqYnBRFV2Qsybu7k/5Hk7kedzCav3onE5+Q4BZxRJLfAVNP1X
      XE4TL51n/eek3gaT2bAvXJ3RGX5kQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-hammer
