sudo: required

services:
  - docker

before_install:
  - docker pull python:2.7.13

script:
  - docker-compose --version
  - docker --version
  - ./travis.sh

notifications:
    email: false

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      q0tR0rX3x167Grld8JZATSG02TqpZqw9FYlldi6peV35/1zZfD8oaEUW14nqM/D5kS/KPeJztKf9cq4McyoSPbPeNVH+Sn5uqLLk2blHpaFKl
      1vNjwYv3hEmbxqad2/DK8vU/VvRsItfJ9C9i2uAXQMfhYX8h6x9vaYNhL/6N386yjr3dEnz3ESCVY+jhA+Ng5tGDpckfcqFJVmaof2P4a8NyB
      CVA4/qU0T4FMht9jhmOAdhUXpNPZclwHCJvrwvsn2Vz9m+fxWjEOSwWIO/Vf2ngkGSu6q0Fsgymrdp1qFcVz5Bazrmfdlt2//+HL3KxcPF3Ht
      2bKDZkoq2dfhw1wuK6ao5C6dYU7nzNcVKFQg0WbLq05JIDm9KQuYw8GQyqO5fnC5FqtpYX94M/asIMoTEoM7nxGj11wTJZAsB/gR82+EEcpZg
      Gan4umy9IbLkmmR6tWKJBBgrLh5mZqPsPJD97e2qwgJ2R2DyStOlMJ/m1YMZz7fBtVR/wi+Wjjzq7ulC94/cTdpq/lFQuAKOpHUkAj2YPDkBU
      cTpktuhXRPLF+9pKBVOIMC+dZge6Uq7wl31FnfuAZAIGsE4JIqntXD82OaEx0EcUSuMsYDP7sO+VD3iX7RXkKh3VMkAfQUcIO++26eIYL/SN4
      G+RsG5/spsA9PEWBhUEwnYXtvI9PM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-hammer
